### ISSUE TITLE
ArcCatalog - a legacy?

### ISSUE THREAD

**Issue by burnsr77** [temple-geography/fundamentals-of-gis#1]
In reference to the "Introduction to ArcGIS" lab.

I think the utility of introducing students to the standalone ArcCatalog long ago went away. It's been integrated into ArcMap for 6 years now and has nearly all the functionality of the standalone. I think you'll find that once you stop using the functionality unique to the standalone, those tasks will increasingly seem outdated and non-useful anyway. Using only the integrated Catalog is more efficient, less confusing, and I think is easier for students to learn.

The biggest reason I'm noting this here, besides the fact that I think our students would do well to learn the latest-and-greatest Arc (and other) functionalities, is that my students had a very hard time keeping straight when to be in ArcMap, ArcCatalog, and Windows Explorer. One student in particular struggled with their initial confusion until the very end of the class.

This semester I took out all mentions of the standalone program and changed all my screenshots to the integrated Catalog. The students _immediately_ understood the software and had no trouble gaining mastery over Catalog that way. It was really quite impressive the improvements that made. I would be happy to submit a pull request with the changes I made.

**Comment by leehach** [comment]
I'd be happy to incorporate those changes.

**Comment by leehach** [comment]
Entirely new set of lab exercises created. ArcCatalog has been removed from early lab activities. Some instructors still prefer it and have included ArcCatalog in their exercises.
